### ISSUE TITLE
Cannot provide browserified versions of all the files in a directory

### ISSUE THREAD

**Issue by robmunro** [gingerhendrix/broccoli-browserify#3]
Would be great if i could just specify a broccoli tree and browserify all files in specific directory (similar to the broccoli-coffeescript module)

eg.

```
  var filterCoffeeScript = require('broccoli-coffee');
  var compileBrowserifyBundles = require('broccoli-browserify');
  var pickFiles = require('broccoli-static-compiler');

  // Build up coffee assets tree for browserify
  var browserifyAssets = 'assets/jsBundles'
  browserifyAssetsTree = pickFiles(browserifyAssets, {
    srcDir: '/',
    files: ['**/*.coffee'],
    destDir: 'jsBundles/' // All files are served from "jsBundles/"?
  });

  // Convert those coffee assets into js
  browserifyAssetsTree = filterCoffeeScript(browserifyAssetsTree, {
    bare: false
  });

  // Build all js files in particular directory
  browserifyAppJs = compileBrowserifyBundles(browserifyAssetsTree, {
    dir: 'jsBundles/'
    outputDir: 'js/
  });

return browserifyAppJs
```

**Comment by gingerhendrix** [comment]
I'm not entirely sure what you're trying to achieve.  The coffeescript plugin works a wee bit differently to browserify.  The coffee compiler turns a tree of coffeescript files into a tree of javascript files, with each file being mapped one-to-one in the output.   Browserify requires one or more entry files and a source tree,  the entry files are parsed for require statements and browserify builds an internal tree containing all the files it's encountered which it outputs to a single file.

What is your expected input/output?  Can you achieve what you want using the browersify command line tool?

**Comment by robmunro** [comment]
I acknowledge they work differently, I guess it would be nice to reduce configuration:) In it's current state I would have to set up a new broccoli-browserify statement for each file i want to browserify, whereas it would be nice to build all files in a particular directory with one statement.

When serving a directory of files using `browserify-middleware` with `express` in node, if i want to serve all files in a particular directory as browserified bundles i just use the following code.

```
app.use('/js', browserify('./client/dir'));
```

I respect this working in a very different way - each file in this directory being browserfied when it is requested, but in order to move over to broccoli I kinda need to replace this:)

I got it to work by using the following:

```
  browserifyDirectory = function (dir, outputDir, tree) {
    browserifiedFiles = []
    files = fs.readdirSync(path.join(__dirname, dir))

    for(var i=0; i < files.length; i++) {

      currentFile = files[i];
      fullpath = path.join(__dirname, dir, currentFile);
      currentFileRelativePath = './' + path.join(dir, currentFile);
      console.log(currentFileRelativePath);

      if(fs.statSync(fullpath).isFile()) {
        browserifiedFiles.push(
          compileBrowserifyBundles(tree, {
            entries: [currentFileRelativePath],
            outputFile: path.join(dir, currentFile) // Required for broccolli-browserify to work
          })
        );
      }
    }
    return browserifiedFiles;
  };

```

Happy to make a pull request for this as part of broccoli-browserify?

**Comment by robmunro** [comment]
Hrmm looking at this again it would be much better to just be using the tree to get the files i want to convert rather than the original files on the file system:) Now to work out how to do that...

**Comment by gingerhendrix** [comment]
I don't think there's a satisfactory implementation for this plugin,  I think this is better handled in your Brocfile.
